module.exports = {
  pageTitle: '.title',
  shoppingCartBadge: '.shopping_cart_badge',
  shoppingCartLink: '.shopping_cart_link',
  burgerMenu: '#react-burger-menu-btn',
  logoutLink: '#logout_sidebar_link',
  inventoryItem: '.inventory_item',
  inventoryItemName: '.inventory_item_name',
  firstInventoryItem: '.inventory_item:first-child',
  addToCartButton: (productName) => `[data-test="add-to-cart-${productName}"]`,
  addToCartButtonFirst: '[data-test^="add-to-cart"]',
  removeButton: (productName) => `[data-test="remove-${productName}"]`,
  removeButtonFirst: '[data-test^="remove"]',
  sortDropdown: '[data-test="product_sort_container"]',
};
